### ISSUE TITLE
Content Discussion: Moving off sam deploy

### ISSUE THREAD

**Issue by nitsujri** [customink/lamby#94]
Again, thanks for all your continued work on this gem + the support elements.

Precursor - I think this should be pure content as opposed to part of the boilerplate. It's an unnecessary complexity and more sugar on top.

One great piece that helps towards that end is using [`AutoPublishAlias: live`](https://github.com/customink/lamby/issues/88#issuecomment-841695363) for blue/green deployments.

Currently, running `bin/_deploy` uses `sam deploy` which waits for the auto-built CodeDeploy to finish its job. In a Canary or a Linear traffic swap situation, the shortest increment of 1 minute but really should be shifting traffic in 3 or 5 minute increments resulting in a 6+ minute deploy cycle.

This means we're paying for Github Actions or CodeBuild to wait while CodeDeploy itself is free. Trivial for small applications, but adds up in business environments.

Personally I'm not there yet. I don't fully understand CodeDeploy, `AutoPublishAlias` is magical, so happy to learn/discuss together if this makes sense.

**Comment by nitsujri** [comment]
Turns out it wasn't so bad, I just needed to follow what other CodeBuild SAM [users are doing](https://stackoverflow.com/a/58442315/399632).

General Steps:

1. `sam package` output `package.yml` or any `template.yml` is spit out as an `artifact` from the CodeBuild stage. 
2. CodePipeline consumes the template and orchestrates CloudFormation to process that file.

Step 2 offloads/acts-as the `sam deploy` to CloudFormation directly. Now that CodePipeline/CloudFormation is handling the `AutoPublishAlias: live` I can let it take as long as it needs.

Let me know if there's a section to be had. Happy to help where it makes sense.

**Comment by metaskills** [comment]
Hey @nitsujri Thanks, I was out the week prior and I'm working thru some old emails. Always appreciate your feedback, some thoughts.

First, let me share that I am not a fan of CodePipeline. For me the complexity of managing that service for deploys is not outweighed by the simplicity of systems like GitHub Actions or CircleCI. That said, I've not yet had the need for an advanced canary deploy option offered by SAM & CodePipeline. If you do, that is fine and why I think a linked blog post from the Lamby site on said topic (or maybe guide) would be helpful. So totally open to doing that.

Second, here is some background on `AutoPublishAlias: live` as to why it is in the starter and mentioned in that Cold Start issue you linked. I have found that when deploying Rails applications that take a descent amount of traffic that the deploy alias will soften the downstream blow of users hitting that application. This happens even when you do not use provisioned concurrency. In fact, the CI/CD system will finish the sam deploy even before traffic is fully rolled over. Often times it takes a minute or two to switch the alias. When you combine that with how it helps soften rollouts in a clean way with less errors... that's all the deploy method I need. 

Again, for me, canaries are kind of moot. We suss out their need in staging. Not to say they are not useful for some and I love the ability. But not the engineering to get there yet because... Code(Deploy|Pipeline) is not super easy. Hence, guide help please.

**Comment by nitsujri** [comment]
> For me the complexity of managing that service for deploys is not outweighed by the simplicity of systems like GitHub Actions or CircleCI.

100% agreed. Having fully gone through the CodePipeline + CodeBuild, I think in the name of focus + ease of upstart, adding this content section is not in the best interest of the project.

I'll close this for now.
